<!DOCTYPE html>
<html>
<head>
    <title>iGOVBot</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>


<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2>
iGOVBot
                </h2>
                iGOVBot — открытый Telegram bot для работы с реестрами украинских компаний. Вопросы, помощь, поддержка — <a href="https://telegram.me/iva220">@iva220</a>

                <?php echo $this->getContent(); ?>


            </div>
        </div>
    </div>
</div>



</body>
</html>